version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dietappdb
    ports:
      - "5432:5432"
    volumes:
      - diet-db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@db:5432/dietappdb?sslmode=disable", "up"]
    volumes:
      - ./backend/db/migrations:/migrations
    depends_on:
      - db

  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dietappdb
    depends_on:
      - db
      - migrate

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      - ./backend/api/openapi.yaml:/spec/openapi.yaml:ro
    depends_on:
      - app
volumes:
  diet-db-data:

