ALTER TABLE patients
    ADD COLUMN surname TEXT NOT NULL,
    ADD COLUMN email TEXT NOT NULL,
    ADD COLUMN age INT NOT NULL,
    ADD COLUMN height REAL NOT NULL,
    ADD COLUMN weight REAL NOT NULL;
